### ISSUE TITLE
functions with more than two arguments throws a TypeError

### ISSUE THREAD

**Issue by k4b7** [bredele/spicy#1]
The following code throws a TypeError:

```
function sum(a,b,c) { return a + b + c; }
curried_sum = curry(sum);
curried_sum(1)(2)(3)
```

**Comment by k4b7** [comment]
I had some examples that I didn't get to in the presentation that show some more functional style things with ES6.  One of the examples shows currying.  Here's what I came up with using ES6:

```
var curry = function(fn) {
    var peel = function(fn, ...args) {
        return args.length === fn.length ? fn(...args) : arg => peel(fn, ...args, arg);
    };
    return peel(fn);
};

var sum = curry(function (a,b,c) { return a + b + c });
sum(1)(2)(3);    // 6
```

One change I would make is to add an optional param to specify the arity because default parameters aren't included in fn.length.

**Comment by bredele** [comment]
@kevinb7 I'm gonna fix that asap.

**Comment by bredele** [comment]
@kevinb7 yup I saw you examples :) I can't wait for ES6 to be widely supported!
